#
# This source file is part of the NeutroFeverGuard based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2025 Stanford University
#
# SPDX-License-Identifier: MIT
#

project: NeutroFeverGuard.xcodeproj
schemes:
- NeutroFeverGuard
